// @ts-check
// Flat config generated by @nuxt/eslint (see .nuxt/eslint.config.mjs after `nuxt prepare`).
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  // Project-wide overrides go here.
)
